# Generated by Django 3.0.3 on 2020-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='maximum_price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='minimum_price',
            field=models.CharField(default=22, max_length=10),
            preserve_default=False,
        ),
    ]
