# Generated by Django 3.0.3 on 2020-04-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200429_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='city_name',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
    ]
